
version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - persist_to_workspace:
          root: .
          paths:
            - android/app/build/outputs/apk/release/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
